### PR TITLE
Implement findReferences and fix range of Variable symbols

### LINKED ISSUE #10: Implement find references
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#find-references

### LINKED ISSUE #44: Variable symbols location are set to their parent's location
They should be set to their own location

### PR DESCRIPTION
**Pull request by natgabb**
Closes #44
Closes #10

### CODE REVIEW

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java [hunk 1]
```diff
@@ -37,17 +39,31 @@
 
     /**
      * Returns a mapping from absolute path of source file to symbols located within these source files.
-     * @return the list of symbols
+     * @return the set of symbols
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java]: can probably just delete the `@return` since it doesn't provide any additional info (and is actually wrong here...)

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 2]
```diff
@@ -64,9 +73,15 @@
     private static final Logger log = LoggerFactory.getLogger(GroovycWrapper.class);
 
     private static final String GROOVY_EXTENSION = "groovy";
+    private static final String GROOVY_DEFAULT_INTERFACE = "groovy.lang.GroovyObject";
+    private static final String JAVA_DEFAULT_OBJECT = "java.lang.Object";
+
     private final Path workspaceRoot;
     private final CompilationUnit unit;
+    // Maps from source file -> list of symbols in that file
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: list -> set

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 3]
```diff
@@ -116,6 +131,61 @@ public Path getWorkspaceRoot() {
     }
 
     @Override
+    public Map<String, Set<SymbolInformation>> getReferences() {
+        return references;
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: so this will return an empty map unless clients call `compile()` first -- is that the intent?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java [hunk 4]
```diff
@@ -37,17 +39,31 @@
...
+     * @return the set of references
+     */
+    Map<String, Set<SymbolInformation>> getReferences();
+
+    /**
+     * Returns the locations of the symbols that reference the symbol defined by the given params.
+     * @param params the parameters used to filter down which symbol is referenced
+     * @return the set of references
+     */
+    Set<Location> findReferences(TextDocumentPositionParams params);
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java]: why does this return `Location` while the method above returns `SymbolInformation`? Seems like `SymbolInformation` would be more useful here as well?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 5]
```diff
@@ -213,13 +315,53 @@ private static SymbolKind getKind(ClassNode node) {
         return SymbolKind.Class;
     }
 
-    private Set<SymbolInformation> getMethodSymbolInformations(String sourcePath, ClassNode parent, MethodNode method) {
+    private SymbolInformation getVariableSymbolInformation(String parentName, String sourcePath, Variable variable) {
+
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: delete extra line

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java (hunk 4 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java]: I made it return `Set<Location>` just because that's what `GroovyTextDocumentService#references` needs to return to the client, but I agree that maybe this interface should return `Set<SymbolInformation>` to be more consistent with the other call.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 6]
```diff
@@ -116,6 +131,61 @@ public Path getWorkspaceRoot() {
...
+        } else {
+            foundSymbol = reduceFoundSymbolsToMostSpecific(foundSymbolInformations, params.getPosition());
+        }
+
+        if (!foundSymbol.isPresent()) {
+            return Sets.newHashSet();
+        }
+
+        String symbolName = foundSymbol.get().getName();
+        if (references.get(symbolName) != null) {
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: using `containsKey()` is generally nicer

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 3 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: Yep I think that's fine! The same will happen with `getFileSymbols`. The alternative would be to have them both throw an exception if `compile()` was never called successfully (without compilation errors) before this was called. Thoughts?

Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: After thinking about it more, I still think this is the nicer solution, because otherwise if the client calls `findReferences` with code that has not compiled successfully it will get an empty list instead of an error.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 7]
```diff
@@ -116,6 +131,61 @@ public Path getWorkspaceRoot() {
...
+            return references.get(symbolName).stream().map(s -> s.getLocation())
+                    .filter(l -> Ranges.isValid(l.getRange())).collect(Collectors.toSet());
+        }
+
+        return Sets.newHashSet();
+    }
+
+    private Optional<SymbolInformation> reduceFoundSymbolsToMostSpecific(Set<SymbolInformation> symbols,
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: I'm not sure how this is the "most specific" symbol? It seems to just be returning the first symbol with a range that encompasses the position?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 8]
```diff
@@ -116,6 +131,61 @@ public Path getWorkspaceRoot() {
...
+                        && Ranges.contains(s.getLocation().getRange(), params.getPosition())
+                        && (s.getKind() == SymbolKind.Class || s.getKind() == SymbolKind.Interface))
+                .collect(Collectors.toSet());
+
+        if (foundSymbolInformations.isEmpty()) {
+            return Sets.newHashSet();
+        }
+
+        Optional<SymbolInformation> foundSymbol;
+        if (foundSymbolInformations.size() == 1) {
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: I think you can call `reduceFoundSymbolsToMostSpecific` even for a set of size 1? in general this code is very if/else-y which makes it concerning in terms of testability.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 9]
```diff
@@ -176,31 +246,63 @@ private void addAllSourcesToCompilationUnit() {
...
-                        Optional.fromNullable(clazz.getOuterClass()).transform(ClassNode::getName)));
+                SymbolInformation classSymbol =
+                        createSymbolInformation(clazz.getName(), getKind(clazz), createLocation(sourcePath, clazz),
+                                Optional.fromNullable(clazz.getOuterClass()).transform(ClassNode::getName));
+                symbols.add(classSymbol);
+
+                // Add implemented interfaces reference
+                for (ClassNode node : clazz.getInterfaces()) {
+                    if (!node.getName().equals(GROOVY_DEFAULT_INTERFACE)) {
+                        newReferences.computeIfAbsent(node.getName(), (value) -> Sets.newHashSet()).add(classSymbol);
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: simpler: `newReferences.putIfAbsent(node.getName(), Sets.newHashSet(classSymbol));`

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 7 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: `GroovycWrapperTest#testFindReferences_edgeCases` has an example for this.
Basically if you have this code:

```
class A {
B myB
class B {}
}
```

Let's say you call `findReferences` with position line 3, char 7. (exactly on top of the defined class B)
When you are iterating through your symbols, you will find two whose ranges contain this position. These symbols will be the class symbols for A and B, because their ranges contain their whole block.
So here in this function we look for the symbol who contains the position only in the first line of their range. Therefore we only find B, since its range starts on line 3.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 10]
```diff
@@ -213,13 +315,53 @@ private static SymbolKind getKind(ClassNode node) {
...
 
-    private Set<SymbolInformation> getMethodSymbolInformations(String sourcePath, ClassNode parent, MethodNode method) {
+    private SymbolInformation getVariableSymbolInformation(String parentName, String sourcePath, Variable variable) {
+
+        Location location;
+        SymbolKind kind;
+
+        if (variable instanceof DynamicVariable) {
+            kind = SymbolKind.Field;
+            location = new LocationBuilder().uri(sourcePath).range(Ranges.createRange(-1, -1, -1, -1)).build();
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: we should define a static variable in `Ranges` to represent -1, -1 , -1, -1

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 7 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: I think it would be cleaner to make this comparison right away in `findReferences` the first time we check if the range contains the position. It'll simplify the code too!

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 11]
```diff
@@ -213,13 +315,53 @@ private static SymbolKind getKind(ClassNode node) {
...
+
+        } else if (variable instanceof FieldNode) {
+            kind = SymbolKind.Field;
+            location = createLocation(sourcePath, (FieldNode) variable);
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: the casting shouldn't be necessary since FieldNode is a ASTNode

Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: Yes but FieldNode extends ASTNode and implements Variable so the casting is needed on variable which is defined as its interface.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 8 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: I think the code in `reduceFoundSymbolsToMostSpecific` can be merged with this method to make all of this simpler.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 9 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: But then I need to check to see if `putIfAbsent` return null (which is what it returns if it was absent) because if its not absent I still need to add the new reference. `putIfAbsent` and `computerIfAbsent` don't return the same thing.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java [hunk 12]
```diff
@@ -91,7 +92,9 @@ public GroovyTextDocumentService(CompilerWrapperProvider provider) {
 
     @Override
     public CompletableFuture<List<? extends Location>> references(ReferenceParams params) {
-        throw new UnsupportedOperationException();
+        return CompletableFuture
+                .completedFuture(provider.get().findReferences(params).stream().map(symbol -> symbol.getLocation())
+                        .filter(location -> Ranges.isValid(location.getRange())).collect(Collectors.toList()));
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java]: Do you know in what cases will the location range be invalid?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 13]
```diff
@@ -64,9 +72,15 @@
     private static final Logger log = LoggerFactory.getLogger(GroovycWrapper.class);
 
     private static final String GROOVY_EXTENSION = "groovy";
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: alphabetize GROOVY_EXTENSION and GROOVY_DEFAULT_INTERFACE

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 3 above)
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: @gracew I think it's a reasonable behavior here. Since even in intelliJ, you won't be able to find all the references without a full build.
@natgabb I remember you told me the reason that you are not calling `compile()` first in `getFileSymbols` is `parseAllSymbols` will take a long time. Looks like it's the same case here. But do you think it's good if we do compile once during initialization? Or should we defer it to the code editor to make the call explicitly

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java (hunk 12 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java]: Yes in the case of generated methods and variables. There are examples in the unit tests.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 3 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: We do compile as soon as a file is opened. But I agree it would be strange that you could not search for symbols unless you opened a file. Finding references on the other hand doesn't matter as much since its based on user interaction with an open file. I think we should consider starting to compile from a new thread in initialize. This is something for a separate PR though.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 14]
```diff
@@ -116,6 +130,48 @@ public Path getWorkspaceRoot() {
...
+        return references;
+    }
+
+    @Override
+    public Set<SymbolInformation> findReferences(ReferenceParams params) {
+        Set<SymbolInformation> symbols = fileSymbols.get(params.getTextDocument().getUri());
+        if (symbols == null) {
+            return Sets.newHashSet();
+        }
+        Set<SymbolInformation> foundSymbolInformations = symbols.stream()
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: is here trying to find the symbol at `params.getPosition()`?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 15]
```diff
@@ -213,13 +301,46 @@ private static SymbolKind getKind(ClassNode node) {
         return SymbolKind.Class;
     }
 
-    private Set<SymbolInformation> getMethodSymbolInformations(String sourcePath, ClassNode parent, MethodNode method) {
+    private SymbolInformation getVariableSymbolInformation(String parentName, String sourcePath, Variable variable) {
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java:297]: I think the parentName here can directly be Optional.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 14 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: Yep! We are trying to find the symbol that intersects the given position, so basically the symbol that the user clicked on.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 15 above)
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java:297]: Actually nvm, seems it's always present and be the class name of the variable

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 16]
```diff
@@ -64,9 +72,15 @@
...
     private static final String GROOVY_EXTENSION = "groovy";
+    private static final String GROOVY_DEFAULT_INTERFACE = "groovy.lang.GroovyObject";
+    private static final String JAVA_DEFAULT_OBJECT = "java.lang.Object";
+
     private final Path workspaceRoot;
     private final CompilationUnit unit;
+    // Maps from source file -> set of symbols in that file
     private Map<String, Set<SymbolInformation>> fileSymbols = Maps.newHashMap();
+    // Maps from type -> set of references of this type
+    private Map<String, Set<SymbolInformation>> references = Maps.newHashMap();
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: We may want to rename this field to classReferences to be clear.
And I imagine after we have the reference information of other types (like local variables), it might still be easier to keep them in different variables

Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: `classReferences` wouldn't really reflect that is contained since it also includes interfaces and enums. Anything that is a type.

Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: We could call it `typeReferences`

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 17]
```diff
@@ -213,13 +301,46 @@ private static SymbolKind getKind(ClassNode node) {
...
+            String sourcePath, ClassNode parent, MethodNode method) {
         Set<SymbolInformation> symbols = Sets.newHashSet();
-        symbols.add(createSymbolInformation(method.getName(), SymbolKind.Method, createLocation(sourcePath, method),
-                Optional.of(parent.getName())));
+
+        SymbolInformation methodSymbol =
+                createSymbolInformation(method.getName(), SymbolKind.Method, createLocation(sourcePath, method),
+                        Optional.of(parent.getName()));
+        symbols.add(methodSymbol);
+        newReferences.computeIfAbsent(method.getReturnType().getName(), (value) -> Sets.newHashSet()).add(methodSymbol);
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: maybe cleaner to add a small helper function called `addToValueSet` that takes in the map, the key and new value in. So that it's easier to know what the command is doing.

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java [hunk 18]
```diff
@@ -80,9 +88,39 @@ public void setup() {
         SymbolInformation symbol = new SymbolInformationBuilder().name("ThisIsASymbol").build();
         symbolsMap.put(WORKSPACE_PATH.resolve("something.groovy").toString(), Sets.newHashSet(symbol));
 
+        expectedReferences.add(new SymbolInformationBuilder()
+                                .containerName("Something")
```
Comment (jiahuijiang) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java]: indentation

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java [hunk 19]
```diff
@@ -162,4 +200,14 @@ public void testDocumentSymbols_relativePath() throws InterruptedException, Exec
                 is(symbolsMap.get(WORKSPACE_PATH.resolve("something.groovy").toString())));
     }
 
+    @Test
+    public void testReferences() throws InterruptedException, ExecutionException {
+        ReferenceParams params =
+                (ReferenceParams) new ReferenceParamsBuilder().context(false).position(5, 5).textDocument("uri")
```
Comment (jiahuijiang) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java:207]: sigh looks like a `ReferenceParamsBuilder` bug and the calls on setting `TextDocumentPositionParams` properties will make it return a TextDocumentPositionParamsBuilder...

Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java:207]: Yeah I filled an issue: https://github.com/TypeFox/ls-api/issues/39

Comment (jiahuijiang) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java:207]: Great! Can you add the ticket number into the comment here so that we can keep track?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 20]
```diff
@@ -116,6 +130,48 @@ public Path getWorkspaceRoot() {
...
+    public Set<SymbolInformation> findReferences(ReferenceParams params) {
+        Set<SymbolInformation> symbols = fileSymbols.get(params.getTextDocument().getUri());
+        if (symbols == null) {
+            return Sets.newHashSet();
+        }
+        Set<SymbolInformation> foundSymbolInformations = symbols.stream()
+                .filter(s -> {
+                    // If we are given a position that is located within the first line of this symbol's location, then
+                    // this is its definition and is likely to be the symbol we are trying to find.
+                    Position startPosition = s.getLocation().getRange().getStart();
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: can we only allow directly clicking on the class name and then check
whether `s.getLocation().getRange()` and `params.getPosition()` is the same?

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java (hunk 12 above)
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java]: I'm imaging for a line looks like `Animal friend = Animal.CAT`, when users want to find references of `Animal`, it should be the `Animal` in this line that's being highlighted. But right now seems the `friend` is being highlighted.

Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java]: I think that should be the intended behavior. If you want to find references of `friend` then it should find all occurrences of this instance of `friend` in the project. This is currently not implemented, because we don't check expressions. As in `Animal anotherAnimal = friend` we don't recognize variable references right now. Also, if you give the position of the type `Animal` then the behavior also makes sense, giving all type references of `Animal`.

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 20 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: So that doesn't work because a range is a series of positions, so you can't just check that they're the same, hence why we check contains. Class symbol ranges don't just cover where their name is defined, but their whole block (from keyword class to their closing curly brace).

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java [hunk 21]
```diff
@@ -91,7 +92,9 @@ public GroovyTextDocumentService(CompilerWrapperProvider provider) {
 
     @Override
     public CompletableFuture<List<? extends Location>> references(ReferenceParams params) {
-        throw new UnsupportedOperationException();
+        return CompletableFuture
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovyTextDocumentService.java]: I find this a bit easier to read as follows:

```
        return CompletableFuture.completedFuture(
                provider.get().findReferences(params).stream()
                        .map(symbol -> symbol.getLocation())
                        .filter(location -> Ranges.isValid(location.getRange()))
                        .collect(Collectors.toList()));
```

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 22]
```diff
@@ -116,6 +129,44 @@ public Path getWorkspaceRoot() {
...
+        if (symbols == null) {
+            return Sets.newHashSet();
+        }
+        List<SymbolInformation> foundSymbolInformations = symbols.stream()
+                .filter(s -> Ranges.isValid(s.getLocation().getRange())
+                            && Ranges.contains(s.getLocation().getRange(), params.getPosition())
+                            && (s.getKind() == SymbolKind.Class || s.getKind() == SymbolKind.Interface
+                                    || s.getKind() == SymbolKind.Enum))
+                // If there is more than one result, we want the symbol whose range starts the latest.
+                .sorted((s1, s2) -> Ranges.POSITION_COMPARATOR.compare(s2.getLocation().getRange().getStart(),
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: it's a bit weird that you compare s1 and s2 in the flipped order so that the latest range comes first in the list. Consider using `Comparator.reverseOrder()` instead

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 23]
```diff
@@ -176,31 +227,61 @@ private void addAllSourcesToCompilationUnit() {
...
                 // Add class symbol
-                symbols.add(createSymbolInformation(clazz.getName(), getKind(clazz), createLocation(sourcePath, clazz),
-                        Optional.fromNullable(clazz.getOuterClass()).transform(ClassNode::getName)));
+                SymbolInformation classSymbol =
+                        createSymbolInformation(clazz.getName(), getKind(clazz), createLocation(sourcePath, clazz),
+                                Optional.fromNullable(clazz.getOuterClass()).transform(ClassNode::getName));
+                symbols.add(classSymbol);
+
+                // Add implemented interfaces reference
+                for (ClassNode node : clazz.getInterfaces()) {
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: prefer for this to be in java 8 to reduce if/else and also to match the rest of this method:

```
                // Add implemented interfaces reference
                Stream.of(clazz.getInterfaces())
                        .filter(node -> !node.getName().equals(GROOVY_DEFAULT_INTERFACE))
                        .forEach(node -> addToValueSet(newTypeReferences, node.getName(), classSymbol));
```

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java [hunk 24]
```diff
@@ -80,9 +88,39 @@ public void setup() {
...
+                .build());
+        Set<SymbolInformation> allReferencesReturned = Sets.newHashSet(expectedReferences);
+        // The reference that will be filtered out
+        allReferencesReturned.add(new SymbolInformationBuilder()
+                .containerName("SomethingElse")
+                .kind(SymbolKind.Class)
+                .name("MyClassName3")
+                .location(new LocationBuilder()
+                            .uri("uri")
+                            .range(Ranges.createRange(-1, -1, -1, -1))
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovyTextDocumentServiceTest.java]: use `Ranges.UNDEFINED_RANGE`

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java [hunk 25]
```diff
@@ -37,17 +38,29 @@
...
+     * Returns a mapping from a type name (class, interface, or enum) to symbols which reference those types.
+     */
+    Map<String, Set<SymbolInformation>> getTypeReferences();
+
+    /**
+     * Returns the locations of the symbols that reference the symbol defined by the given params.
+     * @param params the parameters used to filter down which symbol is referenced
+     * @return the set of locations
+     */
+    Set<SymbolInformation> findReferences(ReferenceParams params);
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java:54]: sorry, I may have asked you this before but why does the typefox `TextDocumentService` return a list here? is there any meaning to the ordering? if so, we should match with List here, otherwise we should stick with set.

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 26]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                + "   InnerCat2 myFriend;\n"
+                + "   class InnerCat2 {\n"
+                + "   }\n"
+                + "}\n");
+        // edge case on one line
+        File enumFile = addFileToFolder(newFolder1, "MyEnum.groovy",
+                "enum MyEnum {ONE,TWO}\n");
+        // edge case on one line
+        File innerClass = addFileToFolder(newFolder1, "AandB.groovy",
+                "public class A {public static class B {}\n"
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: this is a readability thing, but do you mind moving the `public static class B` part onto its own line

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 27]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                        + "A a\n"
+                        + "B b\n"
+                + "}\n");
+        GroovycWrapper wrapper = GroovycWrapper.of(output.getRoot().toPath(), root.getRoot().toPath());
+        Set<Diagnostic> diagnostics = wrapper.compile();
+        assertEquals(0, diagnostics.size());
+
+        // InnerCat2 references - testing finding more specific symbols that are contained inside another symbol's
+        // range.
+        assertEquals(Sets.newHashSet(
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: there's inconsistency between assertEquals and assertThat in this test class -- we should fix this later

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 28]
```diff
@@ -407,4 +982,24 @@ private File addFileToFolder(File parent, String filename, String contents) thro
         return file;
     }
 
+    private static SymbolInformation createSymbolInformation(String name, String uri, SymbolKind kind, int startLine,
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: the number of args is making this unreadable -- consider a helper with the same signature as in `GroovycWrapper` where you pass in a Location directly

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 29]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+        assertEquals(Sets.newHashSet(
+                createSymbolInformation("myFriend", file.getAbsolutePath(),
+                        SymbolKind.Field, 13, 4, 13, 22, Optional.of("Cat2")),
+                createSymbolInformation("getMyFriend", file.getAbsolutePath(),
+                        SymbolKind.Method, -1, -1, -1, -1, Optional.of("Cat2")),
+                createSymbolInformation("value", file.getAbsolutePath(),
+                        SymbolKind.Variable, -1, -1, -1, -1, Optional.of("setMyFriend"))),
+                wrapper.getTypeReferences().get("Cat2$InnerCat2"));
+        // Find one line enum correctly
+        assertEquals(Sets.newHashSet(
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: this is unrelated to the dog/cat example so should be a separate test

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 30]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+        GroovycWrapper wrapper = GroovycWrapper.of(output.getRoot().toPath(), root.getRoot().toPath());
+        Set<Diagnostic> diagnostics = wrapper.compile();
+        assertEquals(0, diagnostics.size());
+
+        // InnerCat2 references - testing finding more specific symbols that are contained inside another symbol's
+        // range.
+        assertEquals(Sets.newHashSet(
+                createSymbolInformation("myFriend", file.getAbsolutePath(),
+                        SymbolKind.Field, 13, 4, 13, 22, Optional.of("Cat2")),
+                createSymbolInformation("getMyFriend", file.getAbsolutePath(),
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: below we filter out the generated results so why do we include them in this test?

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 31]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                        SymbolKind.Field, 3, 1, 3, 4, Optional.of("A"))),
+                wrapper.getTypeReferences().get("A$B").stream()
+                        .filter(symbol -> Ranges.isValid(symbol.getLocation().getRange())).collect(Collectors.toSet()));
+    }
+
+    @Test
+    public void testFindReferences_edgeCases() throws IOException {
+        File newFolder1 = root.newFolder();
+        // edge cases, intersecting ranges
+        File file = addFileToFolder(newFolder1, "Dog.groovy",
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: I would prefer to have 3 different tests for cat/dog, enum, and inner class. then, test `getTypeReferences()` and `findReferences()` in each test

Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: that way you only have to do this set up once

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 32]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+        // edge case on one line
+        File enumFile = addFileToFolder(newFolder1, "MyEnum.groovy",
+                "enum MyEnum {ONE,TWO}\n");
+        // edge case on one line
+        File innerClass = addFileToFolder(newFolder1, "AandB.groovy",
+                "public class A {public static class B {}\n"
+                        + "A a\n"
+                        + "B b\n"
+                + "}\n");
+        GroovycWrapper wrapper = GroovycWrapper.of(output.getRoot().toPath(), root.getRoot().toPath());
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java:496]: I think you should be able to put this in the `@Before`

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java (hunk 25 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/CompilerWrapper.java:54]: The protocol wants an `Location[]` but it doesn't mention if it expects any sort of ordering. It's possible typefox returns a list for flexibility.

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 33]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                        SymbolKind.Field, 3, 1, 3, 4, Optional.of("A"))),
+                wrapper.findReferences(createReferenceParams(innerClass.getAbsolutePath(), 1, 18, false)).stream()
+                .filter(symbol -> Ranges.isValid(symbol.getLocation().getRange())).collect(Collectors.toSet()));
+    }
+
+    @Test
+    public void testReferences_classesAndInterfaces() throws InterruptedException, ExecutionException, IOException {
+        File newFolder1 = root.newFolder();
+        File extendedCoordinatesFile = addFileToFolder(newFolder1, "ExtendedCoordinates.groovy",
+                        "class ExtendedCoordinates extends Coordinates{\n"
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: indentation looks off here

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 34]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                        + "}\n");
+        GroovycWrapper wrapper = GroovycWrapper.of(output.getRoot().toPath(), root.getRoot().toPath());
+        Set<Diagnostic> diagnostics = wrapper.compile();
+        assertEquals(0, diagnostics.size());
+        Map<String, Set<SymbolInformation>> references = wrapper.getTypeReferences();
+        // ExtendedCoordinates should have no references
+        assertNull(references.get("ExtendedCoordinates"));
+        // ExtendedCoordinates2 should have no references
+        assertNull(references.get("ExtendedCoordinates2"));
+        // Coordinates is only referenced in ExtendedCoordinates
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: comment doesn't match code

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 35]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                createSymbolInformation("Coordinates", coordinatesFile.getAbsolutePath(),
+                        SymbolKind.Class, 1, 1, 18, 2, Optional.absent())),
+                references.get("AbstractCoordinates"));
+        // ICoordinatesSuper is only references in ICoordinates
+        assertEquals(Sets.newHashSet(
+                createSymbolInformation("ICoordinates", icoordinatesFile.getAbsolutePath(),
+                        SymbolKind.Interface, 1, 1, 3, 2, Optional.absent())),
+                references.get("ICoordinatesSuper"));
+    }
+
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: extra line

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 33 above)
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: with this many "files" it might make sense to put them in separate files in src/test/resources rather than inlining

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 36]
```diff
@@ -379,18 +383,589 @@ public void testCompile_error() throws InterruptedException, ExecutionException,
...
+                        SymbolKind.Interface, 1, 1, 3, 2, Optional.absent())),
+                wrapper.findReferences(
+                        createReferenceParams(icoordinatesSuperFile.getAbsolutePath(), 1, 14, false)));
+    }
+
+    @Test
+    public void testReferences_fields() throws IOException {
+        File newFolder1 = root.newFolder();
+        File dogFile = addFileToFolder(newFolder1, "Dog.groovy",
+                        "class Dog {\n"
```
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: indentation

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java (hunk 22 above)
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: I'm now using `POSITION_COMPARATOR.reversed()`

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 26 above)
Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: The test is testing for two class declarations on one line. I could put it on its own line without a `\n` but that would be confusing...

**Comment by gracew** [comment]
done reviewing! the main code looks good but there's too much duplication in the test file. feel free to merge after de-duping

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 26 above)
Comment (gracew) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: ah ok. ignore then :)

File: groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java [hunk 37]
```diff
@@ -213,13 +294,45 @@ private static SymbolKind getKind(ClassNode node) {
         return SymbolKind.Class;
     }
 
-    private Set<SymbolInformation> getMethodSymbolInformations(String sourcePath, ClassNode parent, MethodNode method) {
+    private SymbolInformation getVariableSymbolInformation(String parentName, String sourcePath, Variable variable) {
+        Location location;
+        SymbolKind kind;
+        if (variable instanceof DynamicVariable) {
+            kind = SymbolKind.Field;
```
Comment (gracew) [inline groovy-language-server/src/main/java/com/palantir/groovylanguageserver/GroovycWrapper.java]: consider bypassing using `createSymbolInformation` here and just using the builder directly. e.g. 

```
SymbolInformationBuilder builder = new SymbolInformationBuilder().containerName(parentName);
if (variable instanceof DynamicVariable) {
    builder.kind(SymbolKind.Field);
    builder.location(...);
}
```

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 33 above)
Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: The problem is a lot of them are not exactly the same, which would lead to a whole bunch of files like `Coordinates_testReferences_classesAndInterfaces.groovy`.

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 32 above)
Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java:496]: The files need to be created before the wrapper created since it looks through the `workspaceRoot` and adds the sources to the `CompilationUnit`. Also some of the tests need to do things before this is called: `testTargetDirectoryNotFolder` and `testWorkspaceRootNotFolder`.

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 30 above)
Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: It's pretty inconsistent, I'll add them to all the tests!

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 31 above)
Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: I was trying to try to keep the tests smaller, but it makes a lot of sense to merge them especially since they now return very similar results, I can save a lot of duplication even in the expected results.

**Comment by natgabb** [comment]
Thanks for the feedback! :) I just finished de-duping the tests, any more comments @JiahuiJiang ?

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java [hunk 38]
```diff
@@ -57,6 +65,11 @@
     @Rule
     public TemporaryFolder root = new TemporaryFolder();
 
+    @Before
```
Comment (jiahuijiang) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: what's this for?

**Comment by jiahuijiang** [comment]
looks good after one question!

File: groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java (hunk 38 above)
Comment (natgabb) [inline groovy-language-server/src/test/java/com/palantir/groovylanguageserver/GroovycWrapperTest.java]: Oups! I'm going to delete that...
