### PR TITLE
Use LanguageServerLauncher and fix initialization

### LINKED ISSUE #39: Determine which non-deprecated adapter to use
https://github.com/TypeFox/ls-api/issues/38

### PR DESCRIPTION
**Pull request by jiahuijiang**
closes #39

### CODE REVIEW

File: groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java [hunk 1]
```diff
@@ -40,7 +43,7 @@
 @SuppressWarnings("deprecation")
 public final class GroovyLanguageServer implements LanguageServer {
 
-    private static final Logger log = LoggerFactory.getLogger(GroovyLanguageServer.class);
+    private static final Logger LOGGER = LoggerFactory.getLogger(GroovyLanguageServer.class);
```
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java]: I think for loggers the convention is to not user all uppercase naming because it is a constant reference and not a constant value. (http://stackoverflow.com/questions/1417190/should-a-static-final-logger-be-declared-in-upper-case)

Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java]: thanks for the link!

**Comment by natgabb** [comment]
Can you change log -> logger in GroovycWrapper too? :) +1 after that

This is awesome :D so glad to see it work!

File: groovy-language-server/src/main/java/com/palantir/ls/util/LoggerMessageTracer.java [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    public void onError(String message, Throwable throwable) {
+        if (message != null) {
+            logger.error(message);
+        }
+
+        if (throwable != null) {
+            StringWriter stringWriter = new StringWriter();
+            PrintWriter printWriter = new PrintWriter(stringWriter);
+            throwable.printStackTrace(printWriter);
+            String stackTrace = stringWriter.toString();
```
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/ls/util/LoggerMessageTracer.java]: nit: probably don't need to store `stackTrace`

File: groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java [hunk 3]
```diff
@@ -40,7 +43,7 @@
 @SuppressWarnings("deprecation")
```
Comment (natgabb) [inline groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java]: Do we still need this?

File: groovy-language-server/src/main/java/com/palantir/ls/util/LoggerMessageTracer.java (hunk 2 above)
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/ls/util/LoggerMessageTracer.java]: done

File: groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java (hunk 3 above)
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/ls/groovy/GroovyLanguageServer.java]: deleted, and added closes #39

**Comment by natgabb** [comment]
+1 merge whenever
