### PR TITLE
Remove paths from exception messages

### LINKED ISSUE #114: Don't throw exceptions with absolute paths

### PR DESCRIPTION
**Pull request by natgabb**
- Now logs this information and the exception message and stack.

Closes #114

### CODE REVIEW

File: groovy-language-server/src/main/java/com/palantir/ls/server/groovy/GroovyWorkspaceCompiler.java [hunk 1]
```diff
@@ -227,17 +228,19 @@ private void addAllSourcesToCompilationUnit() {
...
-            Throwables.propagate(e);
+            logger.error("Could not delete directory '" + config.getTargetDirectory().toString() + "'", e);
+            throw new RuntimeException("Could not reset compiled files after changes. "
+                    + "Make sure you have permission to modify your target directory.");
+        }
+        if (!config.getTargetDirectory().mkdir()) {
+            logger.error("Could not recreate target directory: '{}'",
+                    config.getTargetDirectory().getAbsolutePath());
+            throw new RuntimeException("Could not reset compiled files after changes. "
+                    + "Make sure you have permission to modify your target directory.");
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/ls/server/groovy/GroovyWorkspaceCompiler.java]: since target directory is created as `Files.createTempDir()`, I don't think users will know how to check the permission. Let's make it `Make sure you have permission to modify your system's  temporary directory`

File: groovy-language-server/src/main/java/com/palantir/ls/server/util/SourceWriter.java [hunk 2]
```diff
@@ -210,8 +214,8 @@ public synchronized void saveChanges() throws IOException {
     private synchronized void initialize() throws IOException {
         if (!destination.toFile().exists() && destination.toFile().isDirectory()) {
             if (!destination.toFile().mkdirs()) {
-                throw new RuntimeException(
-                        String.format("Could not recreate destination directories: %s", destination.toString()));
+                logger.error("Could not recreate destination file '{}'", destination.toString());
+                throw new RuntimeException("Could not recreate destination directories");
```
Comment (jiahuijiang) [inline groovy-language-server/src/main/java/com/palantir/ls/server/util/SourceWriter.java]: add `Make sure you have permission to modify your system's temporary directory` here too

**Comment by jiahuijiang** [comment]
+1 after comments

File: groovy-language-server/src/main/java/com/palantir/ls/server/groovy/GroovyWorkspaceCompiler.java (hunk 1 above)
Comment (natgabb) [reply groovy-language-server/src/main/java/com/palantir/ls/server/groovy/GroovyWorkspaceCompiler.java]: done

Comment (natgabb) [reply groovy-language-server/src/main/java/com/palantir/ls/server/groovy/GroovyWorkspaceCompiler.java]: After talking in person we decided on: `User may not have permission to modify target directory.` since `GroovyWorkspaceCompiler` could be given a non-tmp directory.

File: groovy-language-server/src/main/java/com/palantir/ls/server/util/SourceWriter.java (hunk 2 above)
Comment (natgabb) [reply groovy-language-server/src/main/java/com/palantir/ls/server/util/SourceWriter.java]: done same as above
